// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/anytype-push-server/repo/accountrepo (interfaces: AccountRepo)
//
// Generated by this command:
//
//	mockgen -destination mock_accountrepo/mock_accountrepo.go github.com/anyproto/anytype-push-server/repo/accountrepo AccountRepo
//

// Package mock_accountrepo is a generated GoMock package.
package mock_accountrepo

import (
	context "context"
	reflect "reflect"

	app "github.com/anyproto/any-sync/app"
	domain "github.com/anyproto/anytype-push-server/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepo is a mock of AccountRepo interface.
type MockAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepoMockRecorder
}

// MockAccountRepoMockRecorder is the mock recorder for MockAccountRepo.
type MockAccountRepoMockRecorder struct {
	mock *MockAccountRepo
}

// NewMockAccountRepo creates a new mock instance.
func NewMockAccountRepo(ctrl *gomock.Controller) *MockAccountRepo {
	mock := &MockAccountRepo{ctrl: ctrl}
	mock.recorder = &MockAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepo) EXPECT() *MockAccountRepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAccountRepo) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAccountRepoMockRecorder) Close(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAccountRepo)(nil).Close), arg0)
}

// GetAccountIdsByTopics mocks base method.
func (m *MockAccountRepo) GetAccountIdsByTopics(arg0 context.Context, arg1 []domain.Topic) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIdsByTopics", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdsByTopics indicates an expected call of GetAccountIdsByTopics.
func (mr *MockAccountRepoMockRecorder) GetAccountIdsByTopics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdsByTopics", reflect.TypeOf((*MockAccountRepo)(nil).GetAccountIdsByTopics), arg0, arg1)
}

// GetTopicsByAccountId mocks base method.
func (m *MockAccountRepo) GetTopicsByAccountId(arg0 context.Context, arg1 string) ([]domain.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsByAccountId", arg0, arg1)
	ret0, _ := ret[0].([]domain.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsByAccountId indicates an expected call of GetTopicsByAccountId.
func (mr *MockAccountRepoMockRecorder) GetTopicsByAccountId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsByAccountId", reflect.TypeOf((*MockAccountRepo)(nil).GetTopicsByAccountId), arg0, arg1)
}

// Init mocks base method.
func (m *MockAccountRepo) Init(arg0 *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockAccountRepoMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAccountRepo)(nil).Init), arg0)
}

// Name mocks base method.
func (m *MockAccountRepo) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAccountRepoMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAccountRepo)(nil).Name))
}

// Run mocks base method.
func (m *MockAccountRepo) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAccountRepoMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAccountRepo)(nil).Run), arg0)
}

// SetAccountTopics mocks base method.
func (m *MockAccountRepo) SetAccountTopics(arg0 context.Context, arg1 string, arg2 []domain.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccountTopics", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAccountTopics indicates an expected call of SetAccountTopics.
func (mr *MockAccountRepoMockRecorder) SetAccountTopics(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccountTopics", reflect.TypeOf((*MockAccountRepo)(nil).SetAccountTopics), arg0, arg1, arg2)
}
