// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pushclient/pushapi/protos/push.proto

package pushapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCodes int32

const (
	ErrCodes_Unexpected            ErrCodes = 0
	ErrCodes_InvalidSignature      ErrCodes = 1
	ErrCodes_InvalidTopicSignature ErrCodes = 2
	ErrCodes_SpaceExists           ErrCodes = 3
	ErrCodes_NoValidTopics         ErrCodes = 4
	ErrCodes_ErrorOffset           ErrCodes = 1200
)

// Enum value maps for ErrCodes.
var (
	ErrCodes_name = map[int32]string{
		0:    "Unexpected",
		1:    "InvalidSignature",
		2:    "InvalidTopicSignature",
		3:    "SpaceExists",
		4:    "NoValidTopics",
		1200: "ErrorOffset",
	}
	ErrCodes_value = map[string]int32{
		"Unexpected":            0,
		"InvalidSignature":      1,
		"InvalidTopicSignature": 2,
		"SpaceExists":           3,
		"NoValidTopics":         4,
		"ErrorOffset":           1200,
	}
)

func (x ErrCodes) Enum() *ErrCodes {
	p := new(ErrCodes)
	*p = x
	return p
}

func (x ErrCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_pushclient_pushapi_protos_push_proto_enumTypes[0].Descriptor()
}

func (ErrCodes) Type() protoreflect.EnumType {
	return &file_pushclient_pushapi_protos_push_proto_enumTypes[0]
}

func (x ErrCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCodes.Descriptor instead.
func (ErrCodes) EnumDescriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{0}
}

type Platform int32

const (
	Platform_IOS     Platform = 0
	Platform_Android Platform = 1
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "IOS",
		1: "Android",
	}
	Platform_value = map[string]int32{
		"IOS":     0,
		"Android": 1,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_pushclient_pushapi_protos_push_proto_enumTypes[1].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_pushclient_pushapi_protos_push_proto_enumTypes[1]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{1}
}

type Topics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topics) Reset() {
	*x = Topics{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topics) ProtoMessage() {}

func (x *Topics) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topics.ProtoReflect.Descriptor instead.
func (*Topics) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{0}
}

func (x *Topics) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Topic struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SpaceKey []byte                 `protobuf:"bytes,1,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	Topic    string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// space private key
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetSpaceKey() []byte {
	if x != nil {
		return x.SpaceKey
	}
	return nil
}

func (x *Topic) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Topic) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      Platform               `protobuf:"varint,1,opt,name=platform,proto3,enum=pushproto.Platform" json:"platform,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTokenRequest) Reset() {
	*x = SetTokenRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenRequest) ProtoMessage() {}

func (x *SetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenRequest.ProtoReflect.Descriptor instead.
func (*SetTokenRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{2}
}

func (x *SetTokenRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_IOS
}

func (x *SetTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateSpaceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SpaceKey []byte                 `protobuf:"bytes,1,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	// spacePrivateKey.Sign(identity)
	AccountSignature []byte `protobuf:"bytes,2,opt,name=accountSignature,proto3" json:"accountSignature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSpaceRequest) GetSpaceKey() []byte {
	if x != nil {
		return x.SpaceKey
	}
	return nil
}

func (x *CreateSpaceRequest) GetAccountSignature() []byte {
	if x != nil {
		return x.AccountSignature
	}
	return nil
}

type RemoveSpaceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SpaceKey []byte                 `protobuf:"bytes,1,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	// spacePrivateKey.Sign(identity)
	AccountSignature []byte `protobuf:"bytes,2,opt,name=accountSignature,proto3" json:"accountSignature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveSpaceRequest) Reset() {
	*x = RemoveSpaceRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSpaceRequest) ProtoMessage() {}

func (x *RemoveSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSpaceRequest.ProtoReflect.Descriptor instead.
func (*RemoveSpaceRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSpaceRequest) GetSpaceKey() []byte {
	if x != nil {
		return x.SpaceKey
	}
	return nil
}

func (x *RemoveSpaceRequest) GetAccountSignature() []byte {
	if x != nil {
		return x.AccountSignature
	}
	return nil
}

type SubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsRequest) Reset() {
	*x = SubscriptionsRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsRequest) ProtoMessage() {}

func (x *SubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{5}
}

type SubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        *Topics                `protobuf:"bytes,1,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsResponse) Reset() {
	*x = SubscriptionsResponse{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsResponse) ProtoMessage() {}

func (x *SubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionsResponse) GetTopics() *Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        *Topics                `protobuf:"bytes,1,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRequest) GetTopics() *Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        *Topics                `protobuf:"bytes,1,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{8}
}

func (x *UnsubscribeRequest) GetTopics() *Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type SubscribeAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        *Topics                `protobuf:"bytes,1,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAllRequest) Reset() {
	*x = SubscribeAllRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAllRequest) ProtoMessage() {}

func (x *SubscribeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAllRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAllRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeAllRequest) GetTopics() *Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        *Topics                `protobuf:"bytes,1,opt,name=topics,proto3" json:"topics,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyRequest) GetTopics() *Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *NotifyRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=keyId,proto3" json:"keyId,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_pushclient_pushapi_protos_push_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_pushclient_pushapi_protos_push_proto_rawDescGZIP(), []int{12}
}

var File_pushclient_pushapi_protos_push_proto protoreflect.FileDescriptor

const file_pushclient_pushapi_protos_push_proto_rawDesc = "" +
	"\n" +
	"$pushclient/pushapi/protos/push.proto\x12\tpushproto\"2\n" +
	"\x06Topics\x12(\n" +
	"\x06topics\x18\x01 \x03(\v2\x10.pushproto.TopicR\x06topics\"W\n" +
	"\x05Topic\x12\x1a\n" +
	"\bspaceKey\x18\x01 \x01(\fR\bspaceKey\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"X\n" +
	"\x0fSetTokenRequest\x12/\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x13.pushproto.PlatformR\bplatform\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\\\n" +
	"\x12CreateSpaceRequest\x12\x1a\n" +
	"\bspaceKey\x18\x01 \x01(\fR\bspaceKey\x12*\n" +
	"\x10accountSignature\x18\x02 \x01(\fR\x10accountSignature\"\\\n" +
	"\x12RemoveSpaceRequest\x12\x1a\n" +
	"\bspaceKey\x18\x01 \x01(\fR\bspaceKey\x12*\n" +
	"\x10accountSignature\x18\x02 \x01(\fR\x10accountSignature\"\x16\n" +
	"\x14SubscriptionsRequest\"B\n" +
	"\x15SubscriptionsResponse\x12)\n" +
	"\x06topics\x18\x01 \x01(\v2\x11.pushproto.TopicsR\x06topics\"=\n" +
	"\x10SubscribeRequest\x12)\n" +
	"\x06topics\x18\x01 \x01(\v2\x11.pushproto.TopicsR\x06topics\"?\n" +
	"\x12UnsubscribeRequest\x12)\n" +
	"\x06topics\x18\x01 \x01(\v2\x11.pushproto.TopicsR\x06topics\"@\n" +
	"\x13SubscribeAllRequest\x12)\n" +
	"\x06topics\x18\x01 \x01(\v2\x11.pushproto.TopicsR\x06topics\"h\n" +
	"\rNotifyRequest\x12)\n" +
	"\x06topics\x18\x01 \x01(\v2\x11.pushproto.TopicsR\x06topics\x12,\n" +
	"\amessage\x18\x02 \x01(\v2\x12.pushproto.MessageR\amessage\"W\n" +
	"\aMessage\x12\x14\n" +
	"\x05keyId\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x04\n" +
	"\x02Ok*\x81\x01\n" +
	"\bErrCodes\x12\x0e\n" +
	"\n" +
	"Unexpected\x10\x00\x12\x14\n" +
	"\x10InvalidSignature\x10\x01\x12\x19\n" +
	"\x15InvalidTopicSignature\x10\x02\x12\x0f\n" +
	"\vSpaceExists\x10\x03\x12\x11\n" +
	"\rNoValidTopics\x10\x04\x12\x10\n" +
	"\vErrorOffset\x10\xb0\t* \n" +
	"\bPlatform\x12\a\n" +
	"\x03IOS\x10\x00\x12\v\n" +
	"\aAndroid\x10\x012\xa0\x04\n" +
	"\x04Push\x125\n" +
	"\bSetToken\x12\x1a.pushproto.SetTokenRequest\x1a\r.pushproto.Ok\x12+\n" +
	"\vRevokeToken\x12\r.pushproto.Ok\x1a\r.pushproto.Ok\x12;\n" +
	"\vCreateSpace\x12\x1d.pushproto.CreateSpaceRequest\x1a\r.pushproto.Ok\x12;\n" +
	"\vRemoveSpace\x12\x1d.pushproto.RemoveSpaceRequest\x1a\r.pushproto.Ok\x12R\n" +
	"\rSubscriptions\x12\x1f.pushproto.SubscriptionsRequest\x1a .pushproto.SubscriptionsResponse\x127\n" +
	"\tSubscribe\x12\x1b.pushproto.SubscribeRequest\x1a\r.pushproto.Ok\x12;\n" +
	"\vUnsubscribe\x12\x1d.pushproto.UnsubscribeRequest\x1a\r.pushproto.Ok\x12=\n" +
	"\fSubscribeAll\x12\x1e.pushproto.SubscribeAllRequest\x1a\r.pushproto.Ok\x121\n" +
	"\x06Notify\x12\x18.pushproto.NotifyRequest\x1a\r.pushproto.OkB\x14Z\x12pushclient/pushapib\x06proto3"

var (
	file_pushclient_pushapi_protos_push_proto_rawDescOnce sync.Once
	file_pushclient_pushapi_protos_push_proto_rawDescData []byte
)

func file_pushclient_pushapi_protos_push_proto_rawDescGZIP() []byte {
	file_pushclient_pushapi_protos_push_proto_rawDescOnce.Do(func() {
		file_pushclient_pushapi_protos_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pushclient_pushapi_protos_push_proto_rawDesc), len(file_pushclient_pushapi_protos_push_proto_rawDesc)))
	})
	return file_pushclient_pushapi_protos_push_proto_rawDescData
}

var file_pushclient_pushapi_protos_push_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pushclient_pushapi_protos_push_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pushclient_pushapi_protos_push_proto_goTypes = []any{
	(ErrCodes)(0),                 // 0: pushproto.ErrCodes
	(Platform)(0),                 // 1: pushproto.Platform
	(*Topics)(nil),                // 2: pushproto.Topics
	(*Topic)(nil),                 // 3: pushproto.Topic
	(*SetTokenRequest)(nil),       // 4: pushproto.SetTokenRequest
	(*CreateSpaceRequest)(nil),    // 5: pushproto.CreateSpaceRequest
	(*RemoveSpaceRequest)(nil),    // 6: pushproto.RemoveSpaceRequest
	(*SubscriptionsRequest)(nil),  // 7: pushproto.SubscriptionsRequest
	(*SubscriptionsResponse)(nil), // 8: pushproto.SubscriptionsResponse
	(*SubscribeRequest)(nil),      // 9: pushproto.SubscribeRequest
	(*UnsubscribeRequest)(nil),    // 10: pushproto.UnsubscribeRequest
	(*SubscribeAllRequest)(nil),   // 11: pushproto.SubscribeAllRequest
	(*NotifyRequest)(nil),         // 12: pushproto.NotifyRequest
	(*Message)(nil),               // 13: pushproto.Message
	(*Ok)(nil),                    // 14: pushproto.Ok
}
var file_pushclient_pushapi_protos_push_proto_depIdxs = []int32{
	3,  // 0: pushproto.Topics.topics:type_name -> pushproto.Topic
	1,  // 1: pushproto.SetTokenRequest.platform:type_name -> pushproto.Platform
	2,  // 2: pushproto.SubscriptionsResponse.topics:type_name -> pushproto.Topics
	2,  // 3: pushproto.SubscribeRequest.topics:type_name -> pushproto.Topics
	2,  // 4: pushproto.UnsubscribeRequest.topics:type_name -> pushproto.Topics
	2,  // 5: pushproto.SubscribeAllRequest.topics:type_name -> pushproto.Topics
	2,  // 6: pushproto.NotifyRequest.topics:type_name -> pushproto.Topics
	13, // 7: pushproto.NotifyRequest.message:type_name -> pushproto.Message
	4,  // 8: pushproto.Push.SetToken:input_type -> pushproto.SetTokenRequest
	14, // 9: pushproto.Push.RevokeToken:input_type -> pushproto.Ok
	5,  // 10: pushproto.Push.CreateSpace:input_type -> pushproto.CreateSpaceRequest
	6,  // 11: pushproto.Push.RemoveSpace:input_type -> pushproto.RemoveSpaceRequest
	7,  // 12: pushproto.Push.Subscriptions:input_type -> pushproto.SubscriptionsRequest
	9,  // 13: pushproto.Push.Subscribe:input_type -> pushproto.SubscribeRequest
	10, // 14: pushproto.Push.Unsubscribe:input_type -> pushproto.UnsubscribeRequest
	11, // 15: pushproto.Push.SubscribeAll:input_type -> pushproto.SubscribeAllRequest
	12, // 16: pushproto.Push.Notify:input_type -> pushproto.NotifyRequest
	14, // 17: pushproto.Push.SetToken:output_type -> pushproto.Ok
	14, // 18: pushproto.Push.RevokeToken:output_type -> pushproto.Ok
	14, // 19: pushproto.Push.CreateSpace:output_type -> pushproto.Ok
	14, // 20: pushproto.Push.RemoveSpace:output_type -> pushproto.Ok
	8,  // 21: pushproto.Push.Subscriptions:output_type -> pushproto.SubscriptionsResponse
	14, // 22: pushproto.Push.Subscribe:output_type -> pushproto.Ok
	14, // 23: pushproto.Push.Unsubscribe:output_type -> pushproto.Ok
	14, // 24: pushproto.Push.SubscribeAll:output_type -> pushproto.Ok
	14, // 25: pushproto.Push.Notify:output_type -> pushproto.Ok
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pushclient_pushapi_protos_push_proto_init() }
func file_pushclient_pushapi_protos_push_proto_init() {
	if File_pushclient_pushapi_protos_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pushclient_pushapi_protos_push_proto_rawDesc), len(file_pushclient_pushapi_protos_push_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pushclient_pushapi_protos_push_proto_goTypes,
		DependencyIndexes: file_pushclient_pushapi_protos_push_proto_depIdxs,
		EnumInfos:         file_pushclient_pushapi_protos_push_proto_enumTypes,
		MessageInfos:      file_pushclient_pushapi_protos_push_proto_msgTypes,
	}.Build()
	File_pushclient_pushapi_protos_push_proto = out.File
	file_pushclient_pushapi_protos_push_proto_goTypes = nil
	file_pushclient_pushapi_protos_push_proto_depIdxs = nil
}
