on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release

permissions: write-all

jobs:
  release-reusable:
    uses: anyproto/any-sync-node/.github/workflows/release-reusable.yml@main
    secrets: inherit # pass all secrets
    with:
      start_redis: true
      start_mongodb: true
